### ISSUE TITLE
CocoaPods duplicated name

### ISSUE THREAD

**Issue by pedrommcarrasco** [douglashill/KeyboardKit#1]
Hello @douglashill 👋

There's already a `KeyboardKit` on CocoaPods
https://cocoapods.org/pods/KeyboardKit

Any suggestion? Maybe rename the project/repo? Maybe `Keyboarder`, `KeysKit`, `KeyboardSupportKit`, `KeysetKit`, ... (I'm running out of ideas 😢)

**Comment by douglashill** [comment]
That’s annoying but not that surprising without any namespacing.

Another one: maybe `KeyCommandKit`. However of all these options I think `KeyboardKit` is the best name.

This is only a problem for CocoaPods so what do you think about using a slightly modified name for  the global name there? Some possibilities:

- `Keyboard_Kit`
- `Keyboard+Kit` — if underscore is not allowed
- `KBDKit`
- `DHKeyboardKit` — Objective-C-style

**Comment by pedrommcarrasco** [comment]
What about `Keyboard-Kit`? Looks a little better than the underscore IMO

**Comment by pedrommcarrasco** [comment]
Opened #2 with `Keyboard-Kit` @douglashill 👍

**Comment by douglashill** [comment]
Good call. I like the hyphen. Merged now.
