### ISSUE TITLE
Swift Package Manager support

### ISSUE THREAD

**Issue by sebj** [douglashill/KeyboardKit#9]
It'd be great to have Swift Package Manager support for KeyboardKit. As I think resources and in particular localised string assets aren't supported until the upcoming Swift 5.3 ([SE-0278](https://github.com/apple/swift-evolution/blob/master/proposals/0278-package-manager-localized-resources.md)), that could be a good point at which to fully implement a package definition.

**Comment by sebj** [comment]
Took an early attempt at adding support on a forked branch, without localised asset support (https://github.com/sebj/KeyboardKit/tree/swift-package) – seems to work in a SPM project,  manual building & CocoaPods support were both fine from my testing. Not sure whether it's worth leaving a PR open here or just revisiting after 5.3 support is available in Xcode.

As SPM targets can't contain 'mixed' Objective-C and Swift code, I separated code into two source folders, with the main Swift library target depending on the ObjC target. This only requires the ObjC folder be excluded from the Swift target, and vice-versa for the ObjC target.

The other approach would have been to keep the existing file/folder structure, but define each and every file individually as excluded inside the `Package.swift` file.

The only other issue on that branch besides waiting for Swift 5.3's localised assets is that for some reason 'KeyboardKitObjC' is being exposed as importable alongside 'KeyboardKit', only when the library is used as a Swift Package (CocoaPods same as ever).

**Comment by douglashill** [comment]
Thanks for looking into this @sebj!

I agree with your assessment of the situation. Because localised resource support in SPM is coming soon I think it makes most sense to wait for that. However feel free to open a WIP PR if you like since having that visible might help prevent someone else from redoing work you already did.
